### ISSUE TITLE
LOCALTZ or LOCAL_TZ not necessary?

### ISSUE THREAD

**Issue by alick** [tbabej/task.default-date-time#5]
It seems the advertised `LOCALTZ` (or `LOCAL_TZ`) setup in README is not necessary. Adding this line gives me error like `NameError: name 'pytz' is not defined`

**Comment by tbabej** [comment]
Yes, that's right, time zone is detected in tasklib now. Pull request with updated README would be great!

**Comment by tbabej** [comment]
Resolved with #6.
